// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: api.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	GateId        string                 `protobuf:"bytes,3,opt,name=gate_id,json=gateId,proto3" json:"gate_id,omitempty"`
	ConnId        uint64                 `protobuf:"varint,4,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *LoginReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *LoginReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginReq) GetGateId() string {
	if x != nil {
		return x.GateId
	}
	return ""
}

func (x *LoginReq) GetConnId() uint64 {
	if x != nil {
		return x.ConnId
	}
	return 0
}

type LoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *PlayerBase            `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Bag           *PlayerBag             `protobuf:"bytes,2,opt,name=bag,proto3" json:"bag,omitempty"`
	Quest         *PlayerQuest           `protobuf:"bytes,3,opt,name=quest,proto3" json:"quest,omitempty"`
	Reconnect     bool                   `protobuf:"varint,4,opt,name=reconnect,proto3" json:"reconnect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResp) GetBase() *PlayerBase {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *LoginResp) GetBag() *PlayerBag {
	if x != nil {
		return x.Bag
	}
	return nil
}

func (x *LoginResp) GetQuest() *PlayerQuest {
	if x != nil {
		return x.Quest
	}
	return nil
}

func (x *LoginResp) GetReconnect() bool {
	if x != nil {
		return x.Reconnect
	}
	return false
}

type LogoutReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	GateId        string                 `protobuf:"bytes,2,opt,name=gate_id,json=gateId,proto3" json:"gate_id,omitempty"`
	ConnId        uint64                 `protobuf:"varint,3,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	Reason        uint32                 `protobuf:"varint,4,opt,name=reason,proto3" json:"reason,omitempty"` // 0=主动 1=断线 2=顶号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutReq) Reset() {
	*x = LogoutReq{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutReq) ProtoMessage() {}

func (x *LogoutReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutReq.ProtoReflect.Descriptor instead.
func (*LogoutReq) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *LogoutReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *LogoutReq) GetGateId() string {
	if x != nil {
		return x.GateId
	}
	return ""
}

func (x *LogoutReq) GetConnId() uint64 {
	if x != nil {
		return x.ConnId
	}
	return 0
}

func (x *LogoutReq) GetReason() uint32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

// 顶号下发（push.gate.{gateID}）
type KickNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ConnId        uint64                 `protobuf:"varint,2,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	Reason        uint32                 `protobuf:"varint,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickNotify) Reset() {
	*x = KickNotify{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickNotify) ProtoMessage() {}

func (x *KickNotify) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickNotify.ProtoReflect.Descriptor instead.
func (*KickNotify) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *KickNotify) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *KickNotify) GetConnId() uint64 {
	if x != nil {
		return x.ConnId
	}
	return 0
}

func (x *KickNotify) GetReason() uint32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

func (x *KickNotify) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HeartbeatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientTs      int64                  `protobuf:"varint,1,opt,name=client_ts,json=clientTs,proto3" json:"client_ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatReq) Reset() {
	*x = HeartbeatReq{}
	mi := &file_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatReq) ProtoMessage() {}

func (x *HeartbeatReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatReq.ProtoReflect.Descriptor instead.
func (*HeartbeatReq) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatReq) GetClientTs() int64 {
	if x != nil {
		return x.ClientTs
	}
	return 0
}

type HeartbeatResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerTs      int64                  `protobuf:"varint,1,opt,name=server_ts,json=serverTs,proto3" json:"server_ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResp) Reset() {
	*x = HeartbeatResp{}
	mi := &file_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResp) ProtoMessage() {}

func (x *HeartbeatResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResp.ProtoReflect.Descriptor instead.
func (*HeartbeatResp) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatResp) GetServerTs() int64 {
	if x != nil {
		return x.ServerTs
	}
	return 0
}

type AddCurrencyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      uint32                 `protobuf:"varint,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Delta         int64                  `protobuf:"varint,2,opt,name=delta,proto3" json:"delta,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCurrencyReq) Reset() {
	*x = AddCurrencyReq{}
	mi := &file_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCurrencyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCurrencyReq) ProtoMessage() {}

func (x *AddCurrencyReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCurrencyReq.ProtoReflect.Descriptor instead.
func (*AddCurrencyReq) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{6}
}

func (x *AddCurrencyReq) GetCurrency() uint32 {
	if x != nil {
		return x.Currency
	}
	return 0
}

func (x *AddCurrencyReq) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *AddCurrencyReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type AddCurrencyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       int64                  `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCurrencyResp) Reset() {
	*x = AddCurrencyResp{}
	mi := &file_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCurrencyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCurrencyResp) ProtoMessage() {}

func (x *AddCurrencyResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCurrencyResp.ProtoReflect.Descriptor instead.
func (*AddCurrencyResp) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{7}
}

func (x *AddCurrencyResp) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type AddItemReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TplId         uint32                 `protobuf:"varint,1,opt,name=tpl_id,json=tplId,proto3" json:"tpl_id,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddItemReq) Reset() {
	*x = AddItemReq{}
	mi := &file_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemReq) ProtoMessage() {}

func (x *AddItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemReq.ProtoReflect.Descriptor instead.
func (*AddItemReq) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{8}
}

func (x *AddItemReq) GetTplId() uint32 {
	if x != nil {
		return x.TplId
	}
	return 0
}

func (x *AddItemReq) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *AddItemReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type AddItemResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddItemResp) Reset() {
	*x = AddItemResp{}
	mi := &file_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemResp) ProtoMessage() {}

func (x *AddItemResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemResp.ProtoReflect.Descriptor instead.
func (*AddItemResp) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{9}
}

func (x *AddItemResp) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type UseItemReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    uint64                 `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseItemReq) Reset() {
	*x = UseItemReq{}
	mi := &file_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseItemReq) ProtoMessage() {}

func (x *UseItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseItemReq.ProtoReflect.Descriptor instead.
func (*UseItemReq) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{10}
}

func (x *UseItemReq) GetInstanceId() uint64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *UseItemReq) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type UseItemResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Remain        int64                  `protobuf:"varint,1,opt,name=remain,proto3" json:"remain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseItemResp) Reset() {
	*x = UseItemResp{}
	mi := &file_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseItemResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseItemResp) ProtoMessage() {}

func (x *UseItemResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseItemResp.ProtoReflect.Descriptor instead.
func (*UseItemResp) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{11}
}

func (x *UseItemResp) GetRemain() int64 {
	if x != nil {
		return x.Remain
	}
	return 0
}

type GetBagReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBagReq) Reset() {
	*x = GetBagReq{}
	mi := &file_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBagReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBagReq) ProtoMessage() {}

func (x *GetBagReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBagReq.ProtoReflect.Descriptor instead.
func (*GetBagReq) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{12}
}

type GetBagResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bag           *PlayerBag             `protobuf:"bytes,1,opt,name=bag,proto3" json:"bag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBagResp) Reset() {
	*x = GetBagResp{}
	mi := &file_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBagResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBagResp) ProtoMessage() {}

func (x *GetBagResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBagResp.ProtoReflect.Descriptor instead.
func (*GetBagResp) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{13}
}

func (x *GetBagResp) GetBag() *PlayerBag {
	if x != nil {
		return x.Bag
	}
	return nil
}

type AcceptQuestReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestId       uint32                 `protobuf:"varint,1,opt,name=quest_id,json=questId,proto3" json:"quest_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptQuestReq) Reset() {
	*x = AcceptQuestReq{}
	mi := &file_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptQuestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptQuestReq) ProtoMessage() {}

func (x *AcceptQuestReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptQuestReq.ProtoReflect.Descriptor instead.
func (*AcceptQuestReq) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{14}
}

func (x *AcceptQuestReq) GetQuestId() uint32 {
	if x != nil {
		return x.QuestId
	}
	return 0
}

type QuestProgressReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestId       uint32                 `protobuf:"varint,1,opt,name=quest_id,json=questId,proto3" json:"quest_id,omitempty"`
	Delta         int64                  `protobuf:"varint,2,opt,name=delta,proto3" json:"delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestProgressReq) Reset() {
	*x = QuestProgressReq{}
	mi := &file_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestProgressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestProgressReq) ProtoMessage() {}

func (x *QuestProgressReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestProgressReq.ProtoReflect.Descriptor instead.
func (*QuestProgressReq) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{15}
}

func (x *QuestProgressReq) GetQuestId() uint32 {
	if x != nil {
		return x.QuestId
	}
	return 0
}

func (x *QuestProgressReq) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

type QuestResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quest         *Quest                 `protobuf:"bytes,1,opt,name=quest,proto3" json:"quest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestResp) Reset() {
	*x = QuestResp{}
	mi := &file_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestResp) ProtoMessage() {}

func (x *QuestResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestResp.ProtoReflect.Descriptor instead.
func (*QuestResp) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{16}
}

func (x *QuestResp) GetQuest() *Quest {
	if x != nil {
		return x.Quest
	}
	return nil
}

type GetProfileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uids          []uint64               `protobuf:"varint,1,rep,packed,name=uids,proto3" json:"uids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileReq) Reset() {
	*x = GetProfileReq{}
	mi := &file_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileReq) ProtoMessage() {}

func (x *GetProfileReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileReq.ProtoReflect.Descriptor instead.
func (*GetProfileReq) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{17}
}

func (x *GetProfileReq) GetUids() []uint64 {
	if x != nil {
		return x.Uids
	}
	return nil
}

type GetProfileResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      []*Profile             `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileResp) Reset() {
	*x = GetProfileResp{}
	mi := &file_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResp) ProtoMessage() {}

func (x *GetProfileResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResp.ProtoReflect.Descriptor instead.
func (*GetProfileResp) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{18}
}

func (x *GetProfileResp) GetProfiles() []*Profile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

type AddFriendReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        uint64                 `protobuf:"varint,1,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFriendReq) Reset() {
	*x = AddFriendReq{}
	mi := &file_api_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFriendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFriendReq) ProtoMessage() {}

func (x *AddFriendReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFriendReq.ProtoReflect.Descriptor instead.
func (*AddFriendReq) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{19}
}

func (x *AddFriendReq) GetTarget() uint64 {
	if x != nil {
		return x.Target
	}
	return 0
}

type GetSocialReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSocialReq) Reset() {
	*x = GetSocialReq{}
	mi := &file_api_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSocialReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSocialReq) ProtoMessage() {}

func (x *GetSocialReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSocialReq.ProtoReflect.Descriptor instead.
func (*GetSocialReq) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{20}
}

type GetSocialResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Social        *PlayerSocial          `protobuf:"bytes,1,opt,name=social,proto3" json:"social,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSocialResp) Reset() {
	*x = GetSocialResp{}
	mi := &file_api_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSocialResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSocialResp) ProtoMessage() {}

func (x *GetSocialResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSocialResp.ProtoReflect.Descriptor instead.
func (*GetSocialResp) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{21}
}

func (x *GetSocialResp) GetSocial() *PlayerSocial {
	if x != nil {
		return x.Social
	}
	return nil
}

type GetMailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMailReq) Reset() {
	*x = GetMailReq{}
	mi := &file_api_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMailReq) ProtoMessage() {}

func (x *GetMailReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMailReq.ProtoReflect.Descriptor instead.
func (*GetMailReq) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{22}
}

type GetMailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mail          *PlayerMail            `protobuf:"bytes,1,opt,name=mail,proto3" json:"mail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMailResp) Reset() {
	*x = GetMailResp{}
	mi := &file_api_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMailResp) ProtoMessage() {}

func (x *GetMailResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMailResp.ProtoReflect.Descriptor instead.
func (*GetMailResp) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{23}
}

func (x *GetMailResp) GetMail() *PlayerMail {
	if x != nil {
		return x.Mail
	}
	return nil
}

type ClaimMailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MailId        uint64                 `protobuf:"varint,1,opt,name=mail_id,json=mailId,proto3" json:"mail_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimMailReq) Reset() {
	*x = ClaimMailReq{}
	mi := &file_api_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimMailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimMailReq) ProtoMessage() {}

func (x *ClaimMailReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimMailReq.ProtoReflect.Descriptor instead.
func (*ClaimMailReq) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{24}
}

func (x *ClaimMailReq) GetMailId() uint64 {
	if x != nil {
		return x.MailId
	}
	return 0
}

type ClaimMailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimMailResp) Reset() {
	*x = ClaimMailResp{}
	mi := &file_api_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimMailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimMailResp) ProtoMessage() {}

func (x *ClaimMailResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimMailResp.ProtoReflect.Descriptor instead.
func (*ClaimMailResp) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{25}
}

func (x *ClaimMailResp) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

// L0 写穿：充值 / 开箱，必须幂等（设计文档 §6.2）
type PurchaseReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"` // 客户端唯一订单号
	Product       uint32                 `protobuf:"varint,2,opt,name=product,proto3" json:"product,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseReq) Reset() {
	*x = PurchaseReq{}
	mi := &file_api_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseReq) ProtoMessage() {}

func (x *PurchaseReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseReq.ProtoReflect.Descriptor instead.
func (*PurchaseReq) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{26}
}

func (x *PurchaseReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PurchaseReq) GetProduct() uint32 {
	if x != nil {
		return x.Product
	}
	return 0
}

func (x *PurchaseReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type PurchaseResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       int64                  `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"`
	Duplicate     bool                   `protobuf:"varint,2,opt,name=duplicate,proto3" json:"duplicate,omitempty"` // true 表示返回的是首次结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseResp) Reset() {
	*x = PurchaseResp{}
	mi := &file_api_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseResp) ProtoMessage() {}

func (x *PurchaseResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseResp.ProtoReflect.Descriptor instead.
func (*PurchaseResp) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{27}
}

func (x *PurchaseResp) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *PurchaseResp) GetDuplicate() bool {
	if x != nil {
		return x.Duplicate
	}
	return false
}

type CreateRoomReq struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Mode      uint32                 `protobuf:"varint,1,opt,name=mode,proto3" json:"mode,omitempty"`
	MaxPlayer uint32                 `protobuf:"varint,2,opt,name=max_player,json=maxPlayer,proto3" json:"max_player,omitempty"`
	Members   []uint64               `protobuf:"varint,3,rep,packed,name=members,proto3" json:"members,omitempty"`
	// room_id 由调用方（Match / Lobby）用雪花生成后填入：
	// 房间分片 = room_id % ShardCount，调用方必须据此选择 subject，
	// 因此 ID 只能在调用方产生，不能等到 Room 分片里再生成。
	RoomId        uint64 `protobuf:"varint,4,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomReq) Reset() {
	*x = CreateRoomReq{}
	mi := &file_api_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomReq) ProtoMessage() {}

func (x *CreateRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomReq.ProtoReflect.Descriptor instead.
func (*CreateRoomReq) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{28}
}

func (x *CreateRoomReq) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *CreateRoomReq) GetMaxPlayer() uint32 {
	if x != nil {
		return x.MaxPlayer
	}
	return 0
}

func (x *CreateRoomReq) GetMembers() []uint64 {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *CreateRoomReq) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type CreateRoomResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint64                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomResp) Reset() {
	*x = CreateRoomResp{}
	mi := &file_api_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomResp) ProtoMessage() {}

func (x *CreateRoomResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomResp.ProtoReflect.Descriptor instead.
func (*CreateRoomResp) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{29}
}

func (x *CreateRoomResp) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type JoinRoomReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint64                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Uid           uint64                 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomReq) Reset() {
	*x = JoinRoomReq{}
	mi := &file_api_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomReq) ProtoMessage() {}

func (x *JoinRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomReq.ProtoReflect.Descriptor instead.
func (*JoinRoomReq) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{30}
}

func (x *JoinRoomReq) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *JoinRoomReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type LeaveRoomReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint64                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Uid           uint64                 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomReq) Reset() {
	*x = LeaveRoomReq{}
	mi := &file_api_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomReq) ProtoMessage() {}

func (x *LeaveRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomReq.ProtoReflect.Descriptor instead.
func (*LeaveRoomReq) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{31}
}

func (x *LeaveRoomReq) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *LeaveRoomReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type RoomOpReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint64                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Uid           uint64                 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Op            uint32                 `protobuf:"varint,3,opt,name=op,proto3" json:"op,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomOpReq) Reset() {
	*x = RoomOpReq{}
	mi := &file_api_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomOpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomOpReq) ProtoMessage() {}

func (x *RoomOpReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomOpReq.ProtoReflect.Descriptor instead.
func (*RoomOpReq) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{32}
}

func (x *RoomOpReq) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *RoomOpReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *RoomOpReq) GetOp() uint32 {
	if x != nil {
		return x.Op
	}
	return 0
}

func (x *RoomOpReq) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type RoomSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint64                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Mode          uint32                 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	State         uint32                 `protobuf:"varint,3,opt,name=state,proto3" json:"state,omitempty"` // 0=等待 1=战斗中 2=结算
	Members       []uint64               `protobuf:"varint,4,rep,packed,name=members,proto3" json:"members,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt     int64                  `protobuf:"varint,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	Frame         uint32                 `protobuf:"varint,7,opt,name=frame,proto3" json:"frame,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomSnapshot) Reset() {
	*x = RoomSnapshot{}
	mi := &file_api_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomSnapshot) ProtoMessage() {}

func (x *RoomSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomSnapshot.ProtoReflect.Descriptor instead.
func (*RoomSnapshot) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{33}
}

func (x *RoomSnapshot) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *RoomSnapshot) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *RoomSnapshot) GetState() uint32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *RoomSnapshot) GetMembers() []uint64 {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *RoomSnapshot) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *RoomSnapshot) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *RoomSnapshot) GetFrame() uint32 {
	if x != nil {
		return x.Frame
	}
	return 0
}

type RoomBroadcast struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint64                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Cmd           uint32                 `protobuf:"varint,2,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomBroadcast) Reset() {
	*x = RoomBroadcast{}
	mi := &file_api_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomBroadcast) ProtoMessage() {}

func (x *RoomBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomBroadcast.ProtoReflect.Descriptor instead.
func (*RoomBroadcast) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{34}
}

func (x *RoomBroadcast) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *RoomBroadcast) GetCmd() uint32 {
	if x != nil {
		return x.Cmd
	}
	return 0
}

func (x *RoomBroadcast) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// 网关聚合推送：一条消息带多个 uid（设计文档 §9.3）
type MultiPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uids          []uint64               `protobuf:"varint,1,rep,packed,name=uids,proto3" json:"uids,omitempty"`
	Cmd           uint32                 `protobuf:"varint,2,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiPush) Reset() {
	*x = MultiPush{}
	mi := &file_api_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiPush) ProtoMessage() {}

func (x *MultiPush) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiPush.ProtoReflect.Descriptor instead.
func (*MultiPush) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{35}
}

func (x *MultiPush) GetUids() []uint64 {
	if x != nil {
		return x.Uids
	}
	return nil
}

func (x *MultiPush) GetCmd() uint32 {
	if x != nil {
		return x.Cmd
	}
	return 0
}

func (x *MultiPush) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type BattleResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint64                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	TargetUid     uint64                 `protobuf:"varint,5,opt,name=target_uid,json=targetUid,proto3" json:"target_uid,omitempty"` // job 投递时指明结算目标
	Winners       []uint64               `protobuf:"varint,2,rep,packed,name=winners,proto3" json:"winners,omitempty"`
	Losers        []uint64               `protobuf:"varint,3,rep,packed,name=losers,proto3" json:"losers,omitempty"`
	Score         map[uint64]int64       `protobuf:"bytes,4,rep,name=score,proto3" json:"score,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleResult) Reset() {
	*x = BattleResult{}
	mi := &file_api_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleResult) ProtoMessage() {}

func (x *BattleResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleResult.ProtoReflect.Descriptor instead.
func (*BattleResult) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{36}
}

func (x *BattleResult) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *BattleResult) GetTargetUid() uint64 {
	if x != nil {
		return x.TargetUid
	}
	return 0
}

func (x *BattleResult) GetWinners() []uint64 {
	if x != nil {
		return x.Winners
	}
	return nil
}

func (x *BattleResult) GetLosers() []uint64 {
	if x != nil {
		return x.Losers
	}
	return nil
}

func (x *BattleResult) GetScore() map[uint64]int64 {
	if x != nil {
		return x.Score
	}
	return nil
}

type MatchEnqueueReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Mode          uint32                 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Tier          uint32                 `protobuf:"varint,3,opt,name=tier,proto3" json:"tier,omitempty"`
	Power         uint64                 `protobuf:"varint,4,opt,name=power,proto3" json:"power,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchEnqueueReq) Reset() {
	*x = MatchEnqueueReq{}
	mi := &file_api_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchEnqueueReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchEnqueueReq) ProtoMessage() {}

func (x *MatchEnqueueReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchEnqueueReq.ProtoReflect.Descriptor instead.
func (*MatchEnqueueReq) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{37}
}

func (x *MatchEnqueueReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *MatchEnqueueReq) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *MatchEnqueueReq) GetTier() uint32 {
	if x != nil {
		return x.Tier
	}
	return 0
}

func (x *MatchEnqueueReq) GetPower() uint64 {
	if x != nil {
		return x.Power
	}
	return 0
}

type MatchCancelReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Mode          uint32                 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Tier          uint32                 `protobuf:"varint,3,opt,name=tier,proto3" json:"tier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchCancelReq) Reset() {
	*x = MatchCancelReq{}
	mi := &file_api_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchCancelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchCancelReq) ProtoMessage() {}

func (x *MatchCancelReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchCancelReq.ProtoReflect.Descriptor instead.
func (*MatchCancelReq) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{38}
}

func (x *MatchCancelReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *MatchCancelReq) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *MatchCancelReq) GetTier() uint32 {
	if x != nil {
		return x.Tier
	}
	return 0
}

type MatchAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queued        bool                   `protobuf:"varint,1,opt,name=queued,proto3" json:"queued,omitempty"`
	Position      int32                  `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchAck) Reset() {
	*x = MatchAck{}
	mi := &file_api_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchAck) ProtoMessage() {}

func (x *MatchAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchAck.ProtoReflect.Descriptor instead.
func (*MatchAck) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{39}
}

func (x *MatchAck) GetQueued() bool {
	if x != nil {
		return x.Queued
	}
	return false
}

func (x *MatchAck) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

type MatchFound struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint64                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Mode          uint32                 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Members       []uint64               `protobuf:"varint,3,rep,packed,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchFound) Reset() {
	*x = MatchFound{}
	mi := &file_api_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchFound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchFound) ProtoMessage() {}

func (x *MatchFound) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchFound.ProtoReflect.Descriptor instead.
func (*MatchFound) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{40}
}

func (x *MatchFound) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *MatchFound) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *MatchFound) GetMembers() []uint64 {
	if x != nil {
		return x.Members
	}
	return nil
}

type ChatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       uint32                 `protobuf:"varint,1,opt,name=channel,proto3" json:"channel,omitempty"` // 1=世界 2=公会 3=私聊 4=房间
	From          uint64                 `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	To            uint64                 `protobuf:"varint,3,opt,name=to,proto3" json:"to,omitempty"`
	GuildId       uint64                 `protobuf:"varint,4,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	RoomId        uint64                 `protobuf:"varint,5,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Text          string                 `protobuf:"bytes,6,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatReq) Reset() {
	*x = ChatReq{}
	mi := &file_api_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatReq) ProtoMessage() {}

func (x *ChatReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatReq.ProtoReflect.Descriptor instead.
func (*ChatReq) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{41}
}

func (x *ChatReq) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *ChatReq) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *ChatReq) GetTo() uint64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *ChatReq) GetGuildId() uint64 {
	if x != nil {
		return x.GuildId
	}
	return 0
}

func (x *ChatReq) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *ChatReq) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ChatMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       uint32                 `protobuf:"varint,1,opt,name=channel,proto3" json:"channel,omitempty"`
	From          uint64                 `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	FromNick      string                 `protobuf:"bytes,3,opt,name=from_nick,json=fromNick,proto3" json:"from_nick,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	TsMs          int64                  `protobuf:"varint,5,opt,name=ts_ms,json=tsMs,proto3" json:"ts_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMsg) Reset() {
	*x = ChatMsg{}
	mi := &file_api_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMsg) ProtoMessage() {}

func (x *ChatMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMsg.ProtoReflect.Descriptor instead.
func (*ChatMsg) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{42}
}

func (x *ChatMsg) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *ChatMsg) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *ChatMsg) GetFromNick() string {
	if x != nil {
		return x.FromNick
	}
	return ""
}

func (x *ChatMsg) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ChatMsg) GetTsMs() int64 {
	if x != nil {
		return x.TsMs
	}
	return 0
}

type TransferJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txid          string                 `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	FromUid       uint64                 `protobuf:"varint,2,opt,name=from_uid,json=fromUid,proto3" json:"from_uid,omitempty"`
	ToUid         uint64                 `protobuf:"varint,3,opt,name=to_uid,json=toUid,proto3" json:"to_uid,omitempty"`
	Items         []*Attachment          `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	CurrencyDelta int64                  `protobuf:"varint,5,opt,name=currency_delta,json=currencyDelta,proto3" json:"currency_delta,omitempty"`
	CurrencyType  uint32                 `protobuf:"varint,6,opt,name=currency_type,json=currencyType,proto3" json:"currency_type,omitempty"`
	Reason        string                 `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferJob) Reset() {
	*x = TransferJob{}
	mi := &file_api_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferJob) ProtoMessage() {}

func (x *TransferJob) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferJob.ProtoReflect.Descriptor instead.
func (*TransferJob) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{43}
}

func (x *TransferJob) GetTxid() string {
	if x != nil {
		return x.Txid
	}
	return ""
}

func (x *TransferJob) GetFromUid() uint64 {
	if x != nil {
		return x.FromUid
	}
	return 0
}

func (x *TransferJob) GetToUid() uint64 {
	if x != nil {
		return x.ToUid
	}
	return 0
}

func (x *TransferJob) GetItems() []*Attachment {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *TransferJob) GetCurrencyDelta() int64 {
	if x != nil {
		return x.CurrencyDelta
	}
	return 0
}

func (x *TransferJob) GetCurrencyType() uint32 {
	if x != nil {
		return x.CurrencyType
	}
	return 0
}

func (x *TransferJob) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *TransferJob) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type MailSendJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToUid         uint64                 `protobuf:"varint,1,opt,name=to_uid,json=toUid,proto3" json:"to_uid,omitempty"`
	Mail          *Mail                  `protobuf:"bytes,2,opt,name=mail,proto3" json:"mail,omitempty"`
	Txid          string                 `protobuf:"bytes,3,opt,name=txid,proto3" json:"txid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailSendJob) Reset() {
	*x = MailSendJob{}
	mi := &file_api_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailSendJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailSendJob) ProtoMessage() {}

func (x *MailSendJob) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailSendJob.ProtoReflect.Descriptor instead.
func (*MailSendJob) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{44}
}

func (x *MailSendJob) GetToUid() uint64 {
	if x != nil {
		return x.ToUid
	}
	return 0
}

func (x *MailSendJob) GetMail() *Mail {
	if x != nil {
		return x.Mail
	}
	return nil
}

func (x *MailSendJob) GetTxid() string {
	if x != nil {
		return x.Txid
	}
	return ""
}

type HandoffReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"` // "lobby" / "room"
	Shard         uint32                 `protobuf:"varint,2,opt,name=shard,proto3" json:"shard,omitempty"`
	FromNode      string                 `protobuf:"bytes,3,opt,name=from_node,json=fromNode,proto3" json:"from_node,omitempty"`
	ToNode        string                 `protobuf:"bytes,4,opt,name=to_node,json=toNode,proto3" json:"to_node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandoffReq) Reset() {
	*x = HandoffReq{}
	mi := &file_api_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandoffReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandoffReq) ProtoMessage() {}

func (x *HandoffReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandoffReq.ProtoReflect.Descriptor instead.
func (*HandoffReq) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{45}
}

func (x *HandoffReq) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *HandoffReq) GetShard() uint32 {
	if x != nil {
		return x.Shard
	}
	return 0
}

func (x *HandoffReq) GetFromNode() string {
	if x != nil {
		return x.FromNode
	}
	return ""
}

func (x *HandoffReq) GetToNode() string {
	if x != nil {
		return x.ToNode
	}
	return ""
}

type HandoffResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandoffResp) Reset() {
	*x = HandoffResp{}
	mi := &file_api_proto_msgTypes[46]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandoffResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandoffResp) ProtoMessage() {}

func (x *HandoffResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[46]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandoffResp.ProtoReflect.Descriptor instead.
func (*HandoffResp) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{46}
}

func (x *HandoffResp) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *HandoffResp) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ShutdownReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownReq) Reset() {
	*x = ShutdownReq{}
	mi := &file_api_proto_msgTypes[47]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownReq) ProtoMessage() {}

func (x *ShutdownReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[47]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownReq.ProtoReflect.Descriptor instead.
func (*ShutdownReq) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{47}
}

func (x *ShutdownReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type WorldBossState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BossId        uint64                 `protobuf:"varint,1,opt,name=boss_id,json=bossId,proto3" json:"boss_id,omitempty"`
	Hp            int64                  `protobuf:"varint,2,opt,name=hp,proto3" json:"hp,omitempty"`
	MaxHp         int64                  `protobuf:"varint,3,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	StartedAt     int64                  `protobuf:"varint,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	Alive         bool                   `protobuf:"varint,5,opt,name=alive,proto3" json:"alive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldBossState) Reset() {
	*x = WorldBossState{}
	mi := &file_api_proto_msgTypes[48]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldBossState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldBossState) ProtoMessage() {}

func (x *WorldBossState) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[48]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldBossState.ProtoReflect.Descriptor instead.
func (*WorldBossState) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{48}
}

func (x *WorldBossState) GetBossId() uint64 {
	if x != nil {
		return x.BossId
	}
	return 0
}

func (x *WorldBossState) GetHp() int64 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *WorldBossState) GetMaxHp() int64 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *WorldBossState) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *WorldBossState) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

type WorldBossHitReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Damage        int64                  `protobuf:"varint,2,opt,name=damage,proto3" json:"damage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldBossHitReq) Reset() {
	*x = WorldBossHitReq{}
	mi := &file_api_proto_msgTypes[49]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldBossHitReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldBossHitReq) ProtoMessage() {}

func (x *WorldBossHitReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[49]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldBossHitReq.ProtoReflect.Descriptor instead.
func (*WorldBossHitReq) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{49}
}

func (x *WorldBossHitReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *WorldBossHitReq) GetDamage() int64 {
	if x != nil {
		return x.Damage
	}
	return 0
}

type WorldBossHitResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HpLeft        int64                  `protobuf:"varint,1,opt,name=hp_left,json=hpLeft,proto3" json:"hp_left,omitempty"`
	Killed        bool                   `protobuf:"varint,2,opt,name=killed,proto3" json:"killed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldBossHitResp) Reset() {
	*x = WorldBossHitResp{}
	mi := &file_api_proto_msgTypes[50]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldBossHitResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldBossHitResp) ProtoMessage() {}

func (x *WorldBossHitResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[50]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldBossHitResp.ProtoReflect.Descriptor instead.
func (*WorldBossHitResp) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{50}
}

func (x *WorldBossHitResp) GetHpLeft() int64 {
	if x != nil {
		return x.HpLeft
	}
	return 0
}

func (x *WorldBossHitResp) GetKilled() bool {
	if x != nil {
		return x.Killed
	}
	return false
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\agame.v1\x1a\fplayer.proto\"d\n" +
	"\bLoginReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x17\n" +
	"\agate_id\x18\x03 \x01(\tR\x06gateId\x12\x17\n" +
	"\aconn_id\x18\x04 \x01(\x04R\x06connId\"\xa4\x01\n" +
	"\tLoginResp\x12'\n" +
	"\x04base\x18\x01 \x01(\v2\x13.game.v1.PlayerBaseR\x04base\x12$\n" +
	"\x03bag\x18\x02 \x01(\v2\x12.game.v1.PlayerBagR\x03bag\x12*\n" +
	"\x05quest\x18\x03 \x01(\v2\x14.game.v1.PlayerQuestR\x05quest\x12\x1c\n" +
	"\treconnect\x18\x04 \x01(\bR\treconnect\"g\n" +
	"\tLogoutReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12\x17\n" +
	"\agate_id\x18\x02 \x01(\tR\x06gateId\x12\x17\n" +
	"\aconn_id\x18\x03 \x01(\x04R\x06connId\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\rR\x06reason\"i\n" +
	"\n" +
	"KickNotify\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12\x17\n" +
	"\aconn_id\x18\x02 \x01(\x04R\x06connId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\rR\x06reason\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"+\n" +
	"\fHeartbeatReq\x12\x1b\n" +
	"\tclient_ts\x18\x01 \x01(\x03R\bclientTs\",\n" +
	"\rHeartbeatResp\x12\x1b\n" +
	"\tserver_ts\x18\x01 \x01(\x03R\bserverTs\"Z\n" +
	"\x0eAddCurrencyReq\x12\x1a\n" +
	"\bcurrency\x18\x01 \x01(\rR\bcurrency\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\x03R\x05delta\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"+\n" +
	"\x0fAddCurrencyResp\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x03R\abalance\"Q\n" +
	"\n" +
	"AddItemReq\x12\x15\n" +
	"\x06tpl_id\x18\x01 \x01(\rR\x05tplId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"0\n" +
	"\vAddItemResp\x12!\n" +
	"\x04item\x18\x01 \x01(\v2\r.game.v1.ItemR\x04item\"C\n" +
	"\n" +
	"UseItemReq\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\x04R\n" +
	"instanceId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"%\n" +
	"\vUseItemResp\x12\x16\n" +
	"\x06remain\x18\x01 \x01(\x03R\x06remain\"\v\n" +
	"\tGetBagReq\"2\n" +
	"\n" +
	"GetBagResp\x12$\n" +
	"\x03bag\x18\x01 \x01(\v2\x12.game.v1.PlayerBagR\x03bag\"+\n" +
	"\x0eAcceptQuestReq\x12\x19\n" +
	"\bquest_id\x18\x01 \x01(\rR\aquestId\"C\n" +
	"\x10QuestProgressReq\x12\x19\n" +
	"\bquest_id\x18\x01 \x01(\rR\aquestId\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\x03R\x05delta\"1\n" +
	"\tQuestResp\x12$\n" +
	"\x05quest\x18\x01 \x01(\v2\x0e.game.v1.QuestR\x05quest\"#\n" +
	"\rGetProfileReq\x12\x12\n" +
	"\x04uids\x18\x01 \x03(\x04R\x04uids\">\n" +
	"\x0eGetProfileResp\x12,\n" +
	"\bprofiles\x18\x01 \x03(\v2\x10.game.v1.ProfileR\bprofiles\"&\n" +
	"\fAddFriendReq\x12\x16\n" +
	"\x06target\x18\x01 \x01(\x04R\x06target\"\x0e\n" +
	"\fGetSocialReq\">\n" +
	"\rGetSocialResp\x12-\n" +
	"\x06social\x18\x01 \x01(\v2\x15.game.v1.PlayerSocialR\x06social\"\f\n" +
	"\n" +
	"GetMailReq\"6\n" +
	"\vGetMailResp\x12'\n" +
	"\x04mail\x18\x01 \x01(\v2\x13.game.v1.PlayerMailR\x04mail\"'\n" +
	"\fClaimMailReq\x12\x17\n" +
	"\amail_id\x18\x01 \x01(\x04R\x06mailId\"4\n" +
	"\rClaimMailResp\x12#\n" +
	"\x05items\x18\x01 \x03(\v2\r.game.v1.ItemR\x05items\"Z\n" +
	"\vPurchaseReq\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x18\n" +
	"\aproduct\x18\x02 \x01(\rR\aproduct\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\"F\n" +
	"\fPurchaseResp\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x03R\abalance\x12\x1c\n" +
	"\tduplicate\x18\x02 \x01(\bR\tduplicate\"u\n" +
	"\rCreateRoomReq\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\rR\x04mode\x12\x1d\n" +
	"\n" +
	"max_player\x18\x02 \x01(\rR\tmaxPlayer\x12\x18\n" +
	"\amembers\x18\x03 \x03(\x04R\amembers\x12\x17\n" +
	"\aroom_id\x18\x04 \x01(\x04R\x06roomId\")\n" +
	"\x0eCreateRoomResp\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x04R\x06roomId\"8\n" +
	"\vJoinRoomReq\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x04R\x06roomId\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x04R\x03uid\"9\n" +
	"\fLeaveRoomReq\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x04R\x06roomId\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x04R\x03uid\"`\n" +
	"\tRoomOpReq\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x04R\x06roomId\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x04R\x03uid\x12\x0e\n" +
	"\x02op\x18\x03 \x01(\rR\x02op\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"\xbf\x01\n" +
	"\fRoomSnapshot\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x04R\x06roomId\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\rR\x04mode\x12\x14\n" +
	"\x05state\x18\x03 \x01(\rR\x05state\x12\x18\n" +
	"\amembers\x18\x04 \x03(\x04R\amembers\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"started_at\x18\x06 \x01(\x03R\tstartedAt\x12\x14\n" +
	"\x05frame\x18\a \x01(\rR\x05frame\"T\n" +
	"\rRoomBroadcast\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x04R\x06roomId\x12\x10\n" +
	"\x03cmd\x18\x02 \x01(\rR\x03cmd\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"K\n" +
	"\tMultiPush\x12\x12\n" +
	"\x04uids\x18\x01 \x03(\x04R\x04uids\x12\x10\n" +
	"\x03cmd\x18\x02 \x01(\rR\x03cmd\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"\xea\x01\n" +
	"\fBattleResult\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x04R\x06roomId\x12\x1d\n" +
	"\n" +
	"target_uid\x18\x05 \x01(\x04R\ttargetUid\x12\x18\n" +
	"\awinners\x18\x02 \x03(\x04R\awinners\x12\x16\n" +
	"\x06losers\x18\x03 \x03(\x04R\x06losers\x126\n" +
	"\x05score\x18\x04 \x03(\v2 .game.v1.BattleResult.ScoreEntryR\x05score\x1a8\n" +
	"\n" +
	"ScoreEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"a\n" +
	"\x0fMatchEnqueueReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\rR\x04mode\x12\x12\n" +
	"\x04tier\x18\x03 \x01(\rR\x04tier\x12\x14\n" +
	"\x05power\x18\x04 \x01(\x04R\x05power\"J\n" +
	"\x0eMatchCancelReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\rR\x04mode\x12\x12\n" +
	"\x04tier\x18\x03 \x01(\rR\x04tier\">\n" +
	"\bMatchAck\x12\x16\n" +
	"\x06queued\x18\x01 \x01(\bR\x06queued\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\x05R\bposition\"S\n" +
	"\n" +
	"MatchFound\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x04R\x06roomId\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\rR\x04mode\x12\x18\n" +
	"\amembers\x18\x03 \x03(\x04R\amembers\"\x8f\x01\n" +
	"\aChatReq\x12\x18\n" +
	"\achannel\x18\x01 \x01(\rR\achannel\x12\x12\n" +
	"\x04from\x18\x02 \x01(\x04R\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\x04R\x02to\x12\x19\n" +
	"\bguild_id\x18\x04 \x01(\x04R\aguildId\x12\x17\n" +
	"\aroom_id\x18\x05 \x01(\x04R\x06roomId\x12\x12\n" +
	"\x04text\x18\x06 \x01(\tR\x04text\"}\n" +
	"\aChatMsg\x12\x18\n" +
	"\achannel\x18\x01 \x01(\rR\achannel\x12\x12\n" +
	"\x04from\x18\x02 \x01(\x04R\x04from\x12\x1b\n" +
	"\tfrom_nick\x18\x03 \x01(\tR\bfromNick\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x13\n" +
	"\x05ts_ms\x18\x05 \x01(\x03R\x04tsMs\"\x81\x02\n" +
	"\vTransferJob\x12\x12\n" +
	"\x04txid\x18\x01 \x01(\tR\x04txid\x12\x19\n" +
	"\bfrom_uid\x18\x02 \x01(\x04R\afromUid\x12\x15\n" +
	"\x06to_uid\x18\x03 \x01(\x04R\x05toUid\x12)\n" +
	"\x05items\x18\x04 \x03(\v2\x13.game.v1.AttachmentR\x05items\x12%\n" +
	"\x0ecurrency_delta\x18\x05 \x01(\x03R\rcurrencyDelta\x12#\n" +
	"\rcurrency_type\x18\x06 \x01(\rR\fcurrencyType\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\"[\n" +
	"\vMailSendJob\x12\x15\n" +
	"\x06to_uid\x18\x01 \x01(\x04R\x05toUid\x12!\n" +
	"\x04mail\x18\x02 \x01(\v2\r.game.v1.MailR\x04mail\x12\x12\n" +
	"\x04txid\x18\x03 \x01(\tR\x04txid\"l\n" +
	"\n" +
	"HandoffReq\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x14\n" +
	"\x05shard\x18\x02 \x01(\rR\x05shard\x12\x1b\n" +
	"\tfrom_node\x18\x03 \x01(\tR\bfromNode\x12\x17\n" +
	"\ato_node\x18\x04 \x01(\tR\x06toNode\";\n" +
	"\vHandoffResp\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"%\n" +
	"\vShutdownReq\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\x85\x01\n" +
	"\x0eWorldBossState\x12\x17\n" +
	"\aboss_id\x18\x01 \x01(\x04R\x06bossId\x12\x0e\n" +
	"\x02hp\x18\x02 \x01(\x03R\x02hp\x12\x15\n" +
	"\x06max_hp\x18\x03 \x01(\x03R\x05maxHp\x12\x1d\n" +
	"\n" +
	"started_at\x18\x04 \x01(\x03R\tstartedAt\x12\x14\n" +
	"\x05alive\x18\x05 \x01(\bR\x05alive\";\n" +
	"\x0fWorldBossHitReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12\x16\n" +
	"\x06damage\x18\x02 \x01(\x03R\x06damage\"C\n" +
	"\x10WorldBossHitResp\x12\x17\n" +
	"\ahp_left\x18\x01 \x01(\x03R\x06hpLeft\x12\x16\n" +
	"\x06killed\x18\x02 \x01(\bR\x06killedB!Z\x1fgithub.com/gamedev/f1/pkg/pb;pbb\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 52)
var file_api_proto_goTypes = []any{
	(*LoginReq)(nil),         // 0: game.v1.LoginReq
	(*LoginResp)(nil),        // 1: game.v1.LoginResp
	(*LogoutReq)(nil),        // 2: game.v1.LogoutReq
	(*KickNotify)(nil),       // 3: game.v1.KickNotify
	(*HeartbeatReq)(nil),     // 4: game.v1.HeartbeatReq
	(*HeartbeatResp)(nil),    // 5: game.v1.HeartbeatResp
	(*AddCurrencyReq)(nil),   // 6: game.v1.AddCurrencyReq
	(*AddCurrencyResp)(nil),  // 7: game.v1.AddCurrencyResp
	(*AddItemReq)(nil),       // 8: game.v1.AddItemReq
	(*AddItemResp)(nil),      // 9: game.v1.AddItemResp
	(*UseItemReq)(nil),       // 10: game.v1.UseItemReq
	(*UseItemResp)(nil),      // 11: game.v1.UseItemResp
	(*GetBagReq)(nil),        // 12: game.v1.GetBagReq
	(*GetBagResp)(nil),       // 13: game.v1.GetBagResp
	(*AcceptQuestReq)(nil),   // 14: game.v1.AcceptQuestReq
	(*QuestProgressReq)(nil), // 15: game.v1.QuestProgressReq
	(*QuestResp)(nil),        // 16: game.v1.QuestResp
	(*GetProfileReq)(nil),    // 17: game.v1.GetProfileReq
	(*GetProfileResp)(nil),   // 18: game.v1.GetProfileResp
	(*AddFriendReq)(nil),     // 19: game.v1.AddFriendReq
	(*GetSocialReq)(nil),     // 20: game.v1.GetSocialReq
	(*GetSocialResp)(nil),    // 21: game.v1.GetSocialResp
	(*GetMailReq)(nil),       // 22: game.v1.GetMailReq
	(*GetMailResp)(nil),      // 23: game.v1.GetMailResp
	(*ClaimMailReq)(nil),     // 24: game.v1.ClaimMailReq
	(*ClaimMailResp)(nil),    // 25: game.v1.ClaimMailResp
	(*PurchaseReq)(nil),      // 26: game.v1.PurchaseReq
	(*PurchaseResp)(nil),     // 27: game.v1.PurchaseResp
	(*CreateRoomReq)(nil),    // 28: game.v1.CreateRoomReq
	(*CreateRoomResp)(nil),   // 29: game.v1.CreateRoomResp
	(*JoinRoomReq)(nil),      // 30: game.v1.JoinRoomReq
	(*LeaveRoomReq)(nil),     // 31: game.v1.LeaveRoomReq
	(*RoomOpReq)(nil),        // 32: game.v1.RoomOpReq
	(*RoomSnapshot)(nil),     // 33: game.v1.RoomSnapshot
	(*RoomBroadcast)(nil),    // 34: game.v1.RoomBroadcast
	(*MultiPush)(nil),        // 35: game.v1.MultiPush
	(*BattleResult)(nil),     // 36: game.v1.BattleResult
	(*MatchEnqueueReq)(nil),  // 37: game.v1.MatchEnqueueReq
	(*MatchCancelReq)(nil),   // 38: game.v1.MatchCancelReq
	(*MatchAck)(nil),         // 39: game.v1.MatchAck
	(*MatchFound)(nil),       // 40: game.v1.MatchFound
	(*ChatReq)(nil),          // 41: game.v1.ChatReq
	(*ChatMsg)(nil),          // 42: game.v1.ChatMsg
	(*TransferJob)(nil),      // 43: game.v1.TransferJob
	(*MailSendJob)(nil),      // 44: game.v1.MailSendJob
	(*HandoffReq)(nil),       // 45: game.v1.HandoffReq
	(*HandoffResp)(nil),      // 46: game.v1.HandoffResp
	(*ShutdownReq)(nil),      // 47: game.v1.ShutdownReq
	(*WorldBossState)(nil),   // 48: game.v1.WorldBossState
	(*WorldBossHitReq)(nil),  // 49: game.v1.WorldBossHitReq
	(*WorldBossHitResp)(nil), // 50: game.v1.WorldBossHitResp
	nil,                      // 51: game.v1.BattleResult.ScoreEntry
	(*PlayerBase)(nil),       // 52: game.v1.PlayerBase
	(*PlayerBag)(nil),        // 53: game.v1.PlayerBag
	(*PlayerQuest)(nil),      // 54: game.v1.PlayerQuest
	(*Item)(nil),             // 55: game.v1.Item
	(*Quest)(nil),            // 56: game.v1.Quest
	(*Profile)(nil),          // 57: game.v1.Profile
	(*PlayerSocial)(nil),     // 58: game.v1.PlayerSocial
	(*PlayerMail)(nil),       // 59: game.v1.PlayerMail
	(*Attachment)(nil),       // 60: game.v1.Attachment
	(*Mail)(nil),             // 61: game.v1.Mail
}
var file_api_proto_depIdxs = []int32{
	52, // 0: game.v1.LoginResp.base:type_name -> game.v1.PlayerBase
	53, // 1: game.v1.LoginResp.bag:type_name -> game.v1.PlayerBag
	54, // 2: game.v1.LoginResp.quest:type_name -> game.v1.PlayerQuest
	55, // 3: game.v1.AddItemResp.item:type_name -> game.v1.Item
	53, // 4: game.v1.GetBagResp.bag:type_name -> game.v1.PlayerBag
	56, // 5: game.v1.QuestResp.quest:type_name -> game.v1.Quest
	57, // 6: game.v1.GetProfileResp.profiles:type_name -> game.v1.Profile
	58, // 7: game.v1.GetSocialResp.social:type_name -> game.v1.PlayerSocial
	59, // 8: game.v1.GetMailResp.mail:type_name -> game.v1.PlayerMail
	55, // 9: game.v1.ClaimMailResp.items:type_name -> game.v1.Item
	51, // 10: game.v1.BattleResult.score:type_name -> game.v1.BattleResult.ScoreEntry
	60, // 11: game.v1.TransferJob.items:type_name -> game.v1.Attachment
	61, // 12: game.v1.MailSendJob.mail:type_name -> game.v1.Mail
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	file_player_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   52,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
