// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: envelope.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Envelope 是所有 NATS 消息的统一信封（设计文档 §5.3）。
//
// 演进规则：只增字段不改 tag，废弃字段必须 reserved。
// 滚动发版时新旧版本进程会同时读写同一批数据/消息。
type Envelope struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Cmd      uint32                 `protobuf:"varint,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Uid      uint64                 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	TraceId  string                 `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`    // 全链路追踪，第一天就带上
	FromNode string                 `protobuf:"bytes,4,opt,name=from_node,json=fromNode,proto3" json:"from_node,omitempty"` // 发送方 nodeID
	TsMs     int64                  `protobuf:"varint,5,opt,name=ts_ms,json=tsMs,proto3" json:"ts_ms,omitempty"`
	Seq      uint32                 `protobuf:"varint,6,opt,name=seq,proto3" json:"seq,omitempty"` // 应答匹配
	Body     []byte                 `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	// 应答用：非 0 表示错误码，err_msg 为可读信息。
	ErrCode uint32 `protobuf:"varint,8,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	ErrMsg  string `protobuf:"bytes,9,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	// 目标分片，便于日志与断言（发送方按 uid/roomID 计算后填入）。
	Shard uint32 `protobuf:"varint,10,opt,name=shard,proto3" json:"shard,omitempty"`
	// 内部命令签名（HMAC-SHA256 截断）。
	//
	// Internal / GM 级命令必须携带；接收方用共享密钥校验。
	// 网关不持有这把密钥，因此即使有人伪造出一条内部命令，也过不了校验。
	Auth []byte `protobuf:"bytes,11,opt,name=auth,proto3" json:"auth,omitempty"`
	// 签发 GM 命令的操作者，用于审计（谁补的单）。
	Operator      string `protobuf:"bytes,12,opt,name=operator,proto3" json:"operator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetCmd() uint32 {
	if x != nil {
		return x.Cmd
	}
	return 0
}

func (x *Envelope) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Envelope) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Envelope) GetFromNode() string {
	if x != nil {
		return x.FromNode
	}
	return ""
}

func (x *Envelope) GetTsMs() int64 {
	if x != nil {
		return x.TsMs
	}
	return 0
}

func (x *Envelope) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Envelope) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Envelope) GetErrCode() uint32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *Envelope) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *Envelope) GetShard() uint32 {
	if x != nil {
		return x.Shard
	}
	return 0
}

func (x *Envelope) GetAuth() []byte {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *Envelope) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

// 通用空体 / 通用确认
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{1}
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_envelope_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_envelope_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{2}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_envelope_proto protoreflect.FileDescriptor

const file_envelope_proto_rawDesc = "" +
	"\n" +
	"\x0eenvelope.proto\x12\agame.v1\"\x9b\x02\n" +
	"\bEnvelope\x12\x10\n" +
	"\x03cmd\x18\x01 \x01(\rR\x03cmd\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x04R\x03uid\x12\x19\n" +
	"\btrace_id\x18\x03 \x01(\tR\atraceId\x12\x1b\n" +
	"\tfrom_node\x18\x04 \x01(\tR\bfromNode\x12\x13\n" +
	"\x05ts_ms\x18\x05 \x01(\x03R\x04tsMs\x12\x10\n" +
	"\x03seq\x18\x06 \x01(\rR\x03seq\x12\x12\n" +
	"\x04body\x18\a \x01(\fR\x04body\x12\x19\n" +
	"\berr_code\x18\b \x01(\rR\aerrCode\x12\x17\n" +
	"\aerr_msg\x18\t \x01(\tR\x06errMsg\x12\x14\n" +
	"\x05shard\x18\n" +
	" \x01(\rR\x05shard\x12\x12\n" +
	"\x04auth\x18\v \x01(\fR\x04auth\x12\x1a\n" +
	"\boperator\x18\f \x01(\tR\boperator\"\a\n" +
	"\x05Empty\"\x15\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02okB!Z\x1fgithub.com/gamedev/f1/pkg/pb;pbb\x06proto3"

var (
	file_envelope_proto_rawDescOnce sync.Once
	file_envelope_proto_rawDescData []byte
)

func file_envelope_proto_rawDescGZIP() []byte {
	file_envelope_proto_rawDescOnce.Do(func() {
		file_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_envelope_proto_rawDesc), len(file_envelope_proto_rawDesc)))
	})
	return file_envelope_proto_rawDescData
}

var file_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_envelope_proto_goTypes = []any{
	(*Envelope)(nil), // 0: game.v1.Envelope
	(*Empty)(nil),    // 1: game.v1.Empty
	(*Ack)(nil),      // 2: game.v1.Ack
}
var file_envelope_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_envelope_proto_init() }
func file_envelope_proto_init() {
	if File_envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_envelope_proto_rawDesc), len(file_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_envelope_proto_goTypes,
		DependencyIndexes: file_envelope_proto_depIdxs,
		MessageInfos:      file_envelope_proto_msgTypes,
	}.Build()
	File_envelope_proto = out.File
	file_envelope_proto_goTypes = nil
	file_envelope_proto_depIdxs = nil
}
