// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: player.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerBase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Nick          string                 `protobuf:"bytes,2,opt,name=nick,proto3" json:"nick,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Level         uint32                 `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	Exp           uint64                 `protobuf:"varint,5,opt,name=exp,proto3" json:"exp,omitempty"`
	Currency      map[uint32]int64       `protobuf:"bytes,6,rep,name=currency,proto3" json:"currency,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // CurrencyType -> amount
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastLogin     int64                  `protobuf:"varint,8,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"`
	LastLogout    int64                  `protobuf:"varint,9,opt,name=last_logout,json=lastLogout,proto3" json:"last_logout,omitempty"`
	Power         uint64                 `protobuf:"varint,10,opt,name=power,proto3" json:"power,omitempty"`
	GuildId       uint64                 `protobuf:"varint,11,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerBase) Reset() {
	*x = PlayerBase{}
	mi := &file_player_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerBase) ProtoMessage() {}

func (x *PlayerBase) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerBase.ProtoReflect.Descriptor instead.
func (*PlayerBase) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerBase) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PlayerBase) GetNick() string {
	if x != nil {
		return x.Nick
	}
	return ""
}

func (x *PlayerBase) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *PlayerBase) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *PlayerBase) GetExp() uint64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *PlayerBase) GetCurrency() map[uint32]int64 {
	if x != nil {
		return x.Currency
	}
	return nil
}

func (x *PlayerBase) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *PlayerBase) GetLastLogin() int64 {
	if x != nil {
		return x.LastLogin
	}
	return 0
}

func (x *PlayerBase) GetLastLogout() int64 {
	if x != nil {
		return x.LastLogout
	}
	return 0
}

func (x *PlayerBase) GetPower() uint64 {
	if x != nil {
		return x.Power
	}
	return 0
}

func (x *PlayerBase) GetGuildId() uint64 {
	if x != nil {
		return x.GuildId
	}
	return 0
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    uint64                 `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"` // 雪花 ID，唯一
	TplId         uint32                 `protobuf:"varint,2,opt,name=tpl_id,json=tplId,proto3" json:"tpl_id,omitempty"`
	Count         int64                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	ObtainedAt    int64                  `protobuf:"varint,4,opt,name=obtained_at,json=obtainedAt,proto3" json:"obtained_at,omitempty"`
	Attrs         map[string]int64       `protobuf:"bytes,5,rep,name=attrs,proto3" json:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_player_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{1}
}

func (x *Item) GetInstanceId() uint64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *Item) GetTplId() uint32 {
	if x != nil {
		return x.TplId
	}
	return 0
}

func (x *Item) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Item) GetObtainedAt() int64 {
	if x != nil {
		return x.ObtainedAt
	}
	return 0
}

func (x *Item) GetAttrs() map[string]int64 {
	if x != nil {
		return x.Attrs
	}
	return nil
}

type PlayerBag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Items         []*Item                `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Capacity      uint32                 `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerBag) Reset() {
	*x = PlayerBag{}
	mi := &file_player_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerBag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerBag) ProtoMessage() {}

func (x *PlayerBag) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerBag.ProtoReflect.Descriptor instead.
func (*PlayerBag) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerBag) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PlayerBag) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *PlayerBag) GetCapacity() uint32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

type Quest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestId       uint32                 `protobuf:"varint,1,opt,name=quest_id,json=questId,proto3" json:"quest_id,omitempty"`
	State         uint32                 `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"` // 0=未接 1=进行中 2=可领奖 3=已完成
	Progress      int64                  `protobuf:"varint,3,opt,name=progress,proto3" json:"progress,omitempty"`
	Target        int64                  `protobuf:"varint,4,opt,name=target,proto3" json:"target,omitempty"`
	AcceptAt      int64                  `protobuf:"varint,5,opt,name=accept_at,json=acceptAt,proto3" json:"accept_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quest) Reset() {
	*x = Quest{}
	mi := &file_player_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quest) ProtoMessage() {}

func (x *Quest) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quest.ProtoReflect.Descriptor instead.
func (*Quest) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{3}
}

func (x *Quest) GetQuestId() uint32 {
	if x != nil {
		return x.QuestId
	}
	return 0
}

func (x *Quest) GetState() uint32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *Quest) GetProgress() int64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *Quest) GetTarget() int64 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *Quest) GetAcceptAt() int64 {
	if x != nil {
		return x.AcceptAt
	}
	return 0
}

type PlayerQuest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Quests        []*Quest               `protobuf:"bytes,2,rep,name=quests,proto3" json:"quests,omitempty"`
	DailyResetAt  int64                  `protobuf:"varint,3,opt,name=daily_reset_at,json=dailyResetAt,proto3" json:"daily_reset_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerQuest) Reset() {
	*x = PlayerQuest{}
	mi := &file_player_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerQuest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerQuest) ProtoMessage() {}

func (x *PlayerQuest) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerQuest.ProtoReflect.Descriptor instead.
func (*PlayerQuest) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerQuest) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PlayerQuest) GetQuests() []*Quest {
	if x != nil {
		return x.Quests
	}
	return nil
}

func (x *PlayerQuest) GetDailyResetAt() int64 {
	if x != nil {
		return x.DailyResetAt
	}
	return 0
}

type PlayerSocial struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Friends       []uint64               `protobuf:"varint,2,rep,packed,name=friends,proto3" json:"friends,omitempty"`
	ApplyIn       []uint64               `protobuf:"varint,3,rep,packed,name=apply_in,json=applyIn,proto3" json:"apply_in,omitempty"`
	Blacklist     []uint64               `protobuf:"varint,4,rep,packed,name=blacklist,proto3" json:"blacklist,omitempty"`
	GuildId       uint64                 `protobuf:"varint,5,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerSocial) Reset() {
	*x = PlayerSocial{}
	mi := &file_player_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerSocial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerSocial) ProtoMessage() {}

func (x *PlayerSocial) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerSocial.ProtoReflect.Descriptor instead.
func (*PlayerSocial) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerSocial) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PlayerSocial) GetFriends() []uint64 {
	if x != nil {
		return x.Friends
	}
	return nil
}

func (x *PlayerSocial) GetApplyIn() []uint64 {
	if x != nil {
		return x.ApplyIn
	}
	return nil
}

func (x *PlayerSocial) GetBlacklist() []uint64 {
	if x != nil {
		return x.Blacklist
	}
	return nil
}

func (x *PlayerSocial) GetGuildId() uint64 {
	if x != nil {
		return x.GuildId
	}
	return 0
}

type Mail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MailId        uint64                 `protobuf:"varint,1,opt,name=mail_id,json=mailId,proto3" json:"mail_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Sender        string                 `protobuf:"bytes,4,opt,name=sender,proto3" json:"sender,omitempty"`
	SendAt        int64                  `protobuf:"varint,5,opt,name=send_at,json=sendAt,proto3" json:"send_at,omitempty"`
	ExpireAt      int64                  `protobuf:"varint,6,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	Read          bool                   `protobuf:"varint,7,opt,name=read,proto3" json:"read,omitempty"`
	Claimed       bool                   `protobuf:"varint,8,opt,name=claimed,proto3" json:"claimed,omitempty"`
	Attachments   []*Attachment          `protobuf:"bytes,9,rep,name=attachments,proto3" json:"attachments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mail) Reset() {
	*x = Mail{}
	mi := &file_player_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mail) ProtoMessage() {}

func (x *Mail) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mail.ProtoReflect.Descriptor instead.
func (*Mail) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{6}
}

func (x *Mail) GetMailId() uint64 {
	if x != nil {
		return x.MailId
	}
	return 0
}

func (x *Mail) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Mail) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Mail) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Mail) GetSendAt() int64 {
	if x != nil {
		return x.SendAt
	}
	return 0
}

func (x *Mail) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

func (x *Mail) GetRead() bool {
	if x != nil {
		return x.Read
	}
	return false
}

func (x *Mail) GetClaimed() bool {
	if x != nil {
		return x.Claimed
	}
	return false
}

func (x *Mail) GetAttachments() []*Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

type Attachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TplId         uint32                 `protobuf:"varint,1,opt,name=tpl_id,json=tplId,proto3" json:"tpl_id,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attachment) Reset() {
	*x = Attachment{}
	mi := &file_player_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attachment) ProtoMessage() {}

func (x *Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attachment.ProtoReflect.Descriptor instead.
func (*Attachment) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{7}
}

func (x *Attachment) GetTplId() uint32 {
	if x != nil {
		return x.TplId
	}
	return 0
}

func (x *Attachment) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type PlayerMail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Mails         []*Mail                `protobuf:"bytes,2,rep,name=mails,proto3" json:"mails,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerMail) Reset() {
	*x = PlayerMail{}
	mi := &file_player_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerMail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerMail) ProtoMessage() {}

func (x *PlayerMail) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerMail.ProtoReflect.Descriptor instead.
func (*PlayerMail) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{8}
}

func (x *PlayerMail) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PlayerMail) GetMails() []*Mail {
	if x != nil {
		return x.Mails
	}
	return nil
}

// profile:{uid} 只读摘要（设计文档 §6.5，CQRS 读模型）。
// 以 Redis HASH 存储，任意进程可直读，不唤醒玩家对象。
type Profile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Nick          string                 `protobuf:"bytes,2,opt,name=nick,proto3" json:"nick,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Level         uint32                 `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	GuildId       uint64                 `protobuf:"varint,5,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	Power         uint64                 `protobuf:"varint,6,opt,name=power,proto3" json:"power,omitempty"`
	LastLogin     int64                  `protobuf:"varint,7,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_player_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{9}
}

func (x *Profile) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Profile) GetNick() string {
	if x != nil {
		return x.Nick
	}
	return ""
}

func (x *Profile) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Profile) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Profile) GetGuildId() uint64 {
	if x != nil {
		return x.GuildId
	}
	return 0
}

func (x *Profile) GetPower() uint64 {
	if x != nil {
		return x.Power
	}
	return 0
}

func (x *Profile) GetLastLogin() int64 {
	if x != nil {
		return x.LastLogin
	}
	return 0
}

var File_player_proto protoreflect.FileDescriptor

const file_player_proto_rawDesc = "" +
	"\n" +
	"\fplayer.proto\x12\agame.v1\"\xfe\x02\n" +
	"\n" +
	"PlayerBase\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12\x12\n" +
	"\x04nick\x18\x02 \x01(\tR\x04nick\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x14\n" +
	"\x05level\x18\x04 \x01(\rR\x05level\x12\x10\n" +
	"\x03exp\x18\x05 \x01(\x04R\x03exp\x12=\n" +
	"\bcurrency\x18\x06 \x03(\v2!.game.v1.PlayerBase.CurrencyEntryR\bcurrency\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"last_login\x18\b \x01(\x03R\tlastLogin\x12\x1f\n" +
	"\vlast_logout\x18\t \x01(\x03R\n" +
	"lastLogout\x12\x14\n" +
	"\x05power\x18\n" +
	" \x01(\x04R\x05power\x12\x19\n" +
	"\bguild_id\x18\v \x01(\x04R\aguildId\x1a;\n" +
	"\rCurrencyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xdf\x01\n" +
	"\x04Item\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\x04R\n" +
	"instanceId\x12\x15\n" +
	"\x06tpl_id\x18\x02 \x01(\rR\x05tplId\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x03R\x05count\x12\x1f\n" +
	"\vobtained_at\x18\x04 \x01(\x03R\n" +
	"obtainedAt\x12.\n" +
	"\x05attrs\x18\x05 \x03(\v2\x18.game.v1.Item.AttrsEntryR\x05attrs\x1a8\n" +
	"\n" +
	"AttrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"^\n" +
	"\tPlayerBag\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12#\n" +
	"\x05items\x18\x02 \x03(\v2\r.game.v1.ItemR\x05items\x12\x1a\n" +
	"\bcapacity\x18\x03 \x01(\rR\bcapacity\"\x89\x01\n" +
	"\x05Quest\x12\x19\n" +
	"\bquest_id\x18\x01 \x01(\rR\aquestId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\rR\x05state\x12\x1a\n" +
	"\bprogress\x18\x03 \x01(\x03R\bprogress\x12\x16\n" +
	"\x06target\x18\x04 \x01(\x03R\x06target\x12\x1b\n" +
	"\taccept_at\x18\x05 \x01(\x03R\bacceptAt\"m\n" +
	"\vPlayerQuest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12&\n" +
	"\x06quests\x18\x02 \x03(\v2\x0e.game.v1.QuestR\x06quests\x12$\n" +
	"\x0edaily_reset_at\x18\x03 \x01(\x03R\fdailyResetAt\"\x8e\x01\n" +
	"\fPlayerSocial\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12\x18\n" +
	"\afriends\x18\x02 \x03(\x04R\afriends\x12\x19\n" +
	"\bapply_in\x18\x03 \x03(\x04R\aapplyIn\x12\x1c\n" +
	"\tblacklist\x18\x04 \x03(\x04R\tblacklist\x12\x19\n" +
	"\bguild_id\x18\x05 \x01(\x04R\aguildId\"\x82\x02\n" +
	"\x04Mail\x12\x17\n" +
	"\amail_id\x18\x01 \x01(\x04R\x06mailId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x16\n" +
	"\x06sender\x18\x04 \x01(\tR\x06sender\x12\x17\n" +
	"\asend_at\x18\x05 \x01(\x03R\x06sendAt\x12\x1b\n" +
	"\texpire_at\x18\x06 \x01(\x03R\bexpireAt\x12\x12\n" +
	"\x04read\x18\a \x01(\bR\x04read\x12\x18\n" +
	"\aclaimed\x18\b \x01(\bR\aclaimed\x125\n" +
	"\vattachments\x18\t \x03(\v2\x13.game.v1.AttachmentR\vattachments\"9\n" +
	"\n" +
	"Attachment\x12\x15\n" +
	"\x06tpl_id\x18\x01 \x01(\rR\x05tplId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"C\n" +
	"\n" +
	"PlayerMail\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12#\n" +
	"\x05mails\x18\x02 \x03(\v2\r.game.v1.MailR\x05mails\"\xad\x01\n" +
	"\aProfile\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12\x12\n" +
	"\x04nick\x18\x02 \x01(\tR\x04nick\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x14\n" +
	"\x05level\x18\x04 \x01(\rR\x05level\x12\x19\n" +
	"\bguild_id\x18\x05 \x01(\x04R\aguildId\x12\x14\n" +
	"\x05power\x18\x06 \x01(\x04R\x05power\x12\x1d\n" +
	"\n" +
	"last_login\x18\a \x01(\x03R\tlastLoginB!Z\x1fgithub.com/gamedev/f1/pkg/pb;pbb\x06proto3"

var (
	file_player_proto_rawDescOnce sync.Once
	file_player_proto_rawDescData []byte
)

func file_player_proto_rawDescGZIP() []byte {
	file_player_proto_rawDescOnce.Do(func() {
		file_player_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_player_proto_rawDesc), len(file_player_proto_rawDesc)))
	})
	return file_player_proto_rawDescData
}

var file_player_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_player_proto_goTypes = []any{
	(*PlayerBase)(nil),   // 0: game.v1.PlayerBase
	(*Item)(nil),         // 1: game.v1.Item
	(*PlayerBag)(nil),    // 2: game.v1.PlayerBag
	(*Quest)(nil),        // 3: game.v1.Quest
	(*PlayerQuest)(nil),  // 4: game.v1.PlayerQuest
	(*PlayerSocial)(nil), // 5: game.v1.PlayerSocial
	(*Mail)(nil),         // 6: game.v1.Mail
	(*Attachment)(nil),   // 7: game.v1.Attachment
	(*PlayerMail)(nil),   // 8: game.v1.PlayerMail
	(*Profile)(nil),      // 9: game.v1.Profile
	nil,                  // 10: game.v1.PlayerBase.CurrencyEntry
	nil,                  // 11: game.v1.Item.AttrsEntry
}
var file_player_proto_depIdxs = []int32{
	10, // 0: game.v1.PlayerBase.currency:type_name -> game.v1.PlayerBase.CurrencyEntry
	11, // 1: game.v1.Item.attrs:type_name -> game.v1.Item.AttrsEntry
	1,  // 2: game.v1.PlayerBag.items:type_name -> game.v1.Item
	3,  // 3: game.v1.PlayerQuest.quests:type_name -> game.v1.Quest
	7,  // 4: game.v1.Mail.attachments:type_name -> game.v1.Attachment
	6,  // 5: game.v1.PlayerMail.mails:type_name -> game.v1.Mail
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_player_proto_init() }
func file_player_proto_init() {
	if File_player_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_player_proto_rawDesc), len(file_player_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_player_proto_goTypes,
		DependencyIndexes: file_player_proto_depIdxs,
		MessageInfos:      file_player_proto_msgTypes,
	}.Build()
	File_player_proto = out.File
	file_player_proto_goTypes = nil
	file_player_proto_depIdxs = nil
}
